# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-22 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20180509_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_de',
        ),
    ]
